[project]
name = "multi-object-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SolvedByMac", email = "emeshieobim@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gdown>=5.2.0",
    "numpy>=2.0.0",
    "opencv-python>=4.10.0",
    "scipy>=1.14.0",
    "tensorboard>=2.20.0",
    "torch>=2.5.0",
    "torchreid>=0.2.5",
    "ultralytics>=8.3.0",
]

[project.scripts]
multi-object-tracking = "multi_object_tracking:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.pytest.ini_options]
pythonpath = ["."]